=== grimdomi/Grim-Home/kajona/core/module_packagemanager/docs/xsd/package.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2013 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="target" maxOccurs="1" minOccurs="0"/>
            <xs:element type="typeType" name="type" maxOccurs="1" minOccurs="1" />
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typeType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="MODULE"/>
            <xs:enumeration value="ELEMENT"/>
            <xs:enumeration value="TEMPLATE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== grimdomi/Grim-Home/kajona/core/element_portalupload/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>portalupload</title>
    <description>Provides a way to allow users to upload their own files into the mediamanager via the portal, so without accessing the backend.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
        <module name="mediamanager" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_samplecontent/templates/prolific/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>prolific</title>
    <description>A simple but elegant template</description>
    <version>1.0</version>
    <author>Kajona Team, http://www.freecsstemplates.org/</author>
    <type>TEMPLATE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules />
</package>

=== grimdomi/Grim-Home/kajona/core/element_languageswitch/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>languageswitch</title>
    <description>A simple element to switch the portal-language. Provides a basic logic to avoid language-switches when no content is available in other languages. Takes care of possible languagesets, e.g. for module news.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_pages/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>pages</title>
    <description>Pages are the central part of the system. A page is rendered in the portal and contains several page elements, such as paragraphs, tables or even galleries. The layout is based on the integrated template-engine-</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="mediamanager" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_search/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>search</title>
    <description>The module search provides a full-text search for both, backend and portal. It respects permissions and status of all records.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_eventmanager/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
    >
    <title>eventmanager</title>
    <description>A module to organize events and its participants. Participants may register to events, the number of participants per event is configurable.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_stats/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>stats</title>
    <description>A module analyzing the portal in order to gather statistical data. Renderes charts and other visual reports.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="jqplot" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_formular/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>form</title>
    <description>A simple element providing a contact form. May be used to develop other forms, too.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <target>element_formular</target>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>
