=== grimdomi/Grim-Home/kajona/core/module_packagemanager/docs/xsd/package.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2013 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="target" maxOccurs="1" minOccurs="0"/>
            <xs:element type="typeType" name="type" maxOccurs="1" minOccurs="1" />
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typeType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="MODULE"/>
            <xs:enumeration value="ELEMENT"/>
            <xs:enumeration value="TEMPLATE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== grimdomi/Grim-Home/kajona/core/module_news/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
    >
    <title>news</title>
    <description>Fully fledged news-management. Rss-Feed, categories, and time-based publishing allow flexible and dynamic news-lists.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_directorybrowser/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>directorybrowser</title>
    <description>A simple element to render the content of a folder on the filesystem.</description>
    <version>1.2</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_qrcode/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>qrcode</title>
    <description>QR Codes may be used to generate images containing text-information such as links.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_dashboard/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
    >
    <title>dashboard</title>
    <description>The dashboard is the entry-page of the backend. Current information is displayed by simple widgets.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_rating/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>rating</title>
    <description>Provides a graphical way to your visitors in order to rate content. Therefore the classical stars-approach is used.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_facebooklikebox/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>facebooklikebox</title>
    <description>Want a "like my page on facebook" button on your site? Then this element is yours.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_tags/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>tags</title>
    <description>Tags are used to connect objects with keywords.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_postacomment/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>postacomment</title>
    <description>Postacomment provides users the possibility to add comments to contents.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>
