=== grimdomi/Grim-Home/kajona/core/module_packagemanager/docs/xsd/package.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!--
        (c) 2007-2013 by Kajona, www.kajona.de
        Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt
    -->

    <xs:element name="package" type="packageMetadata" />


    <xs:complexType name="packageMetadata">
        <xs:sequence>
            <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="version" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="author" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="target" maxOccurs="1" minOccurs="0"/>
            <xs:element type="typeType" name="type" maxOccurs="1" minOccurs="1" />
            <xs:element type="boolType" name="providesInstaller" maxOccurs="1" minOccurs="1" />
            <xs:element type="requiredModule" name="requiredModules" maxOccurs="1" minOccurs="1"/>
            <xs:element type="screenshotType" name="screenshots" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="screenshotType">
        <xs:sequence>
            <xs:element name="screenshot" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="requiredModule">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string"/>
                    <xs:attribute name="version" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typeType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="MODULE"/>
            <xs:enumeration value="ELEMENT"/>
            <xs:enumeration value="TEMPLATE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="boolType" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== grimdomi/Grim-Home/kajona/core/module_guestbook/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>guestbook</title>
    <description>A simple module providing a guestbook. New posts may be visible immediately or after an admins' review, depending on the configuration.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_v4skin/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>v4skin</title>
    <description>The basic v4 admin-skin.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>FALSE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_votings/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>votings</title>
    <description>Let your users vote on different polls.</description>
    <version>1.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_portallogin/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>portallogin</title>
    <description>Creates a login-form on your portal-page. If enabled, users are able to change their profile-data and may request a new password (password forgotten functionality).</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_tagto/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>tagto</title>
    <description>A simple element embedding a "tag to service X" box to the current page, e.g. to facebook, google...</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_portalregistration/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>portalregistration</title>
    <description>Allows users to sign up and create an account using the portal.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/element_rssfeed/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>rssfeed</title>
    <description>Include external rss-/atom feeds into your website. This element is used by the complex-pageelement tutorial.</description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>ELEMENT</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
        <module name="pages" version="4.3" />
    </requiredModules>
</package>

=== grimdomi/Grim-Home/kajona/core/module_mediamanager/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://apidocs.kajona.de/xsd/package.xsd"
        >
    <title>mediamanager</title>
    <description>
        The mediamangaer is a central place to handle all kind of files. This includes images for galleries or even a download-manager.
        If you have the package "qr-code" installed, the download links may be illustrated using a qrcode-image, too.
        The mediamanager replaces the old download- and gallery-modules.
    </description>
    <version>4.3</version>
    <author>Kajona Team</author>
    <type>MODULE</type>
    <providesInstaller>TRUE</providesInstaller>
    <requiredModules>
        <module name="system" version="4.3" />
    </requiredModules>
</package>
